### ISSUE TITLE
Crashes sometimes

### ISSUE THREAD

**Issue by takahirox** [takahirox/webgpu-devtools#12]
The WebGPU devtools crashes sometimes. We need to investigate the root issue.

**Comment by mvaligursky** [comment]
I'm trying it with my webgpu code from local host on MacOS (Version 113.0.5672.63 (Official Build) (arm64)), and get this:

```
VM633:3 Uncaught (in promise) TypeError: t.context.createFramebuffer is not a function
    at new t (<anonymous>:3:528930)
    at e.initStateTrackers (<anonymous>:3:563295)
    at new e (<anonymous>:3:562328)
    at new e (<anonymous>:3:587904)
    at e.spyContext (<anonymous>:3:673808)
    at e.trigger (<anonymous>:3:395649)
    at HTMLCanvasElement.t (<anonymous>:3:595157)
    at callFunction (webgpu-devtools.bundle.js:634:23)
    at HTMLCanvasElement.getContext (webgpu-devtools.bundle.js:1892:63)
    at WebgpuGraphicsDevice._callee$ (webgpu-graphics-device.js:212:39)
```

webgpu-devtools.bundle.js:634:23 is this:
![Screenshot 2023-05-03 at 10 39 35](https://user-images.githubusercontent.com/59932779/235882536-aab5c51c-99a0-4c6f-835c-b238ea1ab7d2.png)

**Comment by mvaligursky** [comment]
Note: My crash went away eventually, and I cannot reproduce it currently.

**Comment by takahirox** [comment]
Thanks for the problem report. Sounds like it is a different issue from mine because mine is a crash on devtool panel. I will update the issue comment with details when I will encounter the issue again.

Would you mind opeining another issue?

About a problem you encountered,

> TypeError: t.context.createFramebuffer is not a function

This is suspicious... Because, if I understand correctly, `createFrameBuffer()` is [an API of `WebGLRenderingContext`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/createFramebuffer), not [`GPUCanvasContext`](https://developer.mozilla.org/en-US/docs/Web/API/GPUCanvasContext).

**Comment by mvaligursky** [comment]
> `createFrameBuffer()` is [an API of `WebGLRenderingContext`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/createFramebuffer)

Thanks for pointing this out, I figured it out. When I initialize the engine in WebGL mode, and trigger Spector JS (used to capture WebGL commands), and then switch to WebGPU, this is triggered. I guess we can ignore this, as this is not related to your plugin at all.
